#this script is to pull module colors from WGCNA output and plot their expression
#Danielle Jordan
#16.11.23

#Load libraries 
library(WGCNA)
library(flashClust)
library(edgeR)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(sva)
library(statmod)
library(Dict)
library(naniar)
library(data.table)
library(RColorBrewer)
library(reshape2)
library(wesanderson)
library(ggsci)
library(ggrepel)
library(systemfonts)
library(svglite)

#Read in RData generated by HPC 
load("Network_allSamples_signed_nomerge_RLDfiltered_exp.RData")

#read in log_bros 
log_bros_num <- read.csv("log_bros.csv", row.names = "row.names", stringsAsFactors = FALSE, header = TRUE)

#Read in log_bros that will be used for pulling modules out 
log_bros <- read.csv("bros_filtered.csv", check.names = FALSE, stringsAsFactors = FALSE, header = TRUE)

#Pull modules from colors and make them their own value 
pink_list <- names(log_bros_num)[moduleColors == "pink"]

magenta_list <- names(log_bros_num)[moduleColors == "magenta"]

red_list <- names(log_bros_num)[moduleColors == "red"]

#Convert lists to dataframe 
pink <- as.data.frame(pink_list)

magenta <- as.data.frame(magenta_list)

magenta <- as.data.frame(magenta_list)

#Rename column names to "genes" 
colnames(green) <- c("genes")
colnames(lightcyan) <- c("genes")
colnames(pink) <- c("genes")

#Filter modules out from dataframe to get expression data 
subset_green <- filter(log_bros, log_bros$genes %in% green$genes)

subset_lightcyan <- filter(log_bros, log_bros$genes %in% lightcyan$genes)

subset_pink <- filter(log_bros, log_bros$genes %in%  pink$genes)

#Write filtered modules out as csv 
write.csv(subset_green, file = "subset_green.csv")

write.csv(subset_lightcyan, file = "subset_lightcyan.csv")

write.csv(subset_pink, file = "subset_pink.csv")

#Change module format 
#Transpose data 
transposed_green <- t(subset_green)

transposed_lightcyan <- t(subset_lightcyan)

transposed_pink <- t(subset_pink)

#Set first row as column names
colnames(transposed_green) <- transposed_green[1,]
transposed_green <- transposed_green[-1, ] 

colnames(transposed_lightcyan) <- transposed_lightcyan[1,]
transposed_lightcyan <- transposed_lightcyan[-1, ] 

colnames(transposed_pink) <- transposed_pink[1,]
transposed_pink <- transposed_pink[-1, ] 

#Convert transposed data back into dataframe 
transposed_green <- data.frame(transposed_green)

transposed_lightcyan <- data.frame(transposed_lightcyan)

transposed_pink <- data.frame(transposed_pink)

#Add column "x" that holds numeric values for each library
transposed_green$X <- c(1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
                          6, 6, 6, 6, 7, 7, 7)

transposed_lightcyan$X <- c(1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
                          6, 6, 6, 6, 7, 7, 7)

transposed_pink$X <- c(1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
                           6, 6, 6, 6, 7, 7, 7)

#Set "x" as first column
transposed_green <- transposed_green[, c("X", setdiff(names(transposed_green), "X"))]

transposed_lightcyan <- transposed_lightcyan[, c("X", setdiff(names(transposed_lightcyan), "X"))]

transposed_pink <- transposed_pink[, c("X", setdiff(names(transposed_pink), "X"))]

#Plot green
melted_green <- melt(transposed_green, id.vars = "X", variable.name = "gene.ID", value.name = "expression" )
head(melted_green)

melted_green$expression <- as.numeric(melted_green$expression)

agg_green <- aggregate(
  x = melted_green[c("expression")],
  by = melted_green[c("gene.ID","X")],
  FUN = mean, na.rm = TRUE)

tiff('Green_module_expression.tiff', width = 4.5, height = 1.8, units = 'in', res = 650)

ggplot(data=agg_green, aes(x=jitter(agg_green$X),y=agg_green$expression)) +
  geom_point(size = 0.1, colour="grey", alpha=0.8) +
  geom_path(aes(x=agg_green$X,y=agg_green$expression, group=agg_green$gene.ID), size=0.2, colour="grey", alpha=0.5, linetype="dotted") +
  geom_smooth(level=0.95, colour="green", size=0.5 ,fill="green", alpha=0.5) +
  scale_y_continuous(trans = 'log2', limits= c(2, 4000)) +
  scale_x_continuous(breaks = seq(1,7,1)) +
  labs(x = "Developmental Stage", y = "FPKM") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "black")) 

dev.off()

#Plot lightcyan
melted_lightcyan <- melt(transposed_lightcyan, id.vars = "X", variable.name = "gene.ID", value.name = "expression" )
head(melted_lightcyan)

melted_lightcyan$expression <- as.numeric(melted_lightcyan$expression)

agg_lightcyan <- aggregate(
  x = melted_lightcyan[c("expression")],
  by = melted_lightcyan[c("gene.ID","X")],
  FUN = mean, na.rm = TRUE)

tiff('LightCyan_module_expression.tiff', width = 4.5, height = 1.8, units = 'in', res = 650)

ggplot(data=agg_lightcyan, aes(x=jitter(agg_lightcyan$X),y=agg_lightcyan$expression)) +
  geom_point(size = 0.1, colour="grey", alpha=0.8) +
  geom_path(aes(x=agg_lightcyan$X,y=agg_lightcyan$expression, group=agg_lightcyan$gene.ID), size=0.2, colour="grey", alpha=0.5, linetype="dotted") +
  geom_smooth(level=0.95, colour="lightcyan", size=0.5 ,fill="lightcyan", alpha=0.5) +
  scale_y_continuous(trans = 'log2', limits= c(2, 4000)) +
  scale_x_continuous(breaks = seq(1,7,1)) +
  labs(x = "Developmental Stage", y = "FPKM") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "black")) 

dev.off()

#Plot pink
melted_pink <- melt(transposed_pink, id.vars = "X", variable.name = "gene.ID", value.name = "expression" )
head(melted_pink)

melted_pink$expression <- as.numeric(melted_pink$expression)

agg_pink <- aggregate(
  x = melted_pink[c("expression")],
  by = melted_pink[c("gene.ID","X")],
  FUN = mean, na.rm = TRUE)

tiff('Pink_module_expression.tiff', width = 4.5, height = 1.8, units = 'in', res = 650)

ggplot(data=agg_pink, aes(x=jitter(agg_pink$X),y=agg_pink$expression)) +
  geom_point(size = 0.1, colour="grey", alpha=0.8) +
  geom_path(aes(x=agg_pink$X,y=agg_pink$expression, group=agg_pink$gene.ID), size=0.2, colour="grey", alpha=0.5, linetype="dotted") +
  geom_smooth(level=0.95, colour="pink", size=0.5 ,fill="pink", alpha=0.5) +
  scale_y_continuous(trans = 'log2', limits= c(2, 4000)) +
  scale_x_continuous(breaks = seq(1,7,1)) +
  labs(x = "Developmental Stage", y = "FPKM") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "black")) 

dev.off()

#Pulling annotation information using module lists to identify specific genes in each module 

#Read in pairwise annotation file 
evlv_ann <- read.csv("merge_all.csv", stringsAsFactors = FALSE, header = TRUE, sep = ",")

#Read in whole transcriptome annotation files 
human_ann <- read.csv("swissprot_human_whole_trxm.csv", stringsAsFactors = FALSE, header = TRUE, sep = ",")

whole_ann <- read.csv("swissprot_all_whole_trxm.csv", stringsAsFactors = FALSE, header = TRUE, sep = ",")

#Filter annotated gene ids from module list
#Green
evlv_ann_green <- filter(evlv_ann, evlv_ann$genes %in% green$genes)

human_green <- filter(human_ann, human_ann$genes %in% green$genes)

all_green <- filter(whole_ann, whole_ann$genes %in% green$genes)

#LightCyan
evlv_lightcyan <- filter(evlv_ann, evlv_ann$genes %in% lightcyan$genes)

human_lightcyan <- filter(human_ann, human_ann$genes %in% lightcyan$genes)

all_lightcyan <- filter(whole_ann, whole_ann$genes %in% lightcyan$genes)

#Pink
evlv_pink <- filter(evlv_ann, evlv_ann$genes %in% pink$genes)

human_pink <- filter(human_ann, human_ann$genes %in% pink$genes)

all_pink <- filter(whole_ann, whole_ann$genes %in% pink$genes)

