#this script is to pull module colors from WGCNA output and plot their expression
#Danielle Jordan

#Load libraries 
library(WGCNA)
library(flashClust)
library(edgeR)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(sva)
library(statmod)
library(Dict)
library(naniar)
library(data.table)
library(RColorBrewer)
library(reshape2)
library(wesanderson)
library(ggsci)
library(ggrepel)
library(systemfonts)
library(svglite)

#Read in RData generated by HPC 
load("Network_allSamples_signed_nomerge_RLDfiltered.RData")

#read in log_bros 
log_bros_num <- read.csv("log_bros.csv", row.names = "row.names", stringsAsFactors = FALSE, header = TRUE)

#Read in log_bros that will be used for pulling modules out 
log_bros <- read.csv("bros_filtered.csv", check.names = FALSE, stringsAsFactors = FALSE, header = TRUE)

#Read in list of mistake candidates
id_list_regulators <-read.table("candidates_regulators.txt", header = TRUE)

id_list_direct <-read.table("candidates_direct.txt", header = TRUE)

#Pull modules from colors and make them their own value 
red_list <- names(log_bros_num)[moduleColors == "red"]

magenta_list <- names(log_bros_num)[moduleColors == "magenta"]

pink_list <- names(log_bros_num)[moduleColors == "pink"]

salmon_list <- names(log_bros_num)[moduleColors == "salmon"]

green_list <- names(log_bros_num)[moduleColors == "green"]

#Convert lists to dataframe 
red <- as.data.frame(red_list)

magenta <- as.data.frame(magenta_list)

pink <- as.data.frame(pink_list)

salmon <- as.data.frame(salmon_list)

green <- as.data.frame(green_list)
#Rename column names to "genes" 
colnames(red) <- c("genes")
colnames(magenta) <- c("genes")
colnames(pink) <- c("genes")
colnames(salmon) <- c("genes")
colnames(green) <- c("genes")

#Filter modules out from dataframe to get expression data 
subset_red <- filter(log_bros, log_bros$genes %in% red$genes)

subset_magenta <- filter(log_bros, log_bros$genes %in% magenta$genes)

subset_pink <- filter(log_bros, log_bros$genes %in%  pink$genes)

subset_salmon <-filter(log_bros, log_bros$genes %in% salmon$genes)

subset_green <- filter(log_bros, log_bros$genes %in% green$genes)

#Write filtered modules out as csv 
write.csv(subset_red, file = "subset_red.csv")

write.csv(subset_magenta, file = "subset_magenta.csv")

write.csv(subset_pink, file = "subset_pink.csv")

write.csv(subset_salmon, file = "subset_salmon.csv")

write.csv(subset_green, file = "subset_green.csv")

#Change module format 
#Transpose data 
transposed_red <- t(subset_red)

transposed_magenta <- t(subset_magenta)

transposed_pink <- t(subset_pink)

transposed_salmon <- t(subset_salmon)

transposed_green <- t(subset_green)

#Set first row as column names
colnames(transposed_red) <- transposed_red[1,]
transposed_red <- transposed_red[-1, ] 

colnames(transposed_magenta) <- transposed_magenta[1,]
transposed_magenta <- transposed_magenta[-1, ] 

colnames(transposed_pink) <- transposed_pink[1,]
transposed_pink <- transposed_pink[-1, ] 

colnames(transposed_salmon) <- transposed_salmon[1,]
transposed_salmon <- transposed_salmon[-1, ] 

colnames(transposed_green) <- transposed_green[1,]
transposed_green <- transposed_green[-1, ] 

#Convert transposed data back into dataframe 
transposed_red <- data.frame(transposed_red)

transposed_magenta <- data.frame(transposed_magenta)

transposed_pink <- data.frame(transposed_pink)

transposed_salmon <-data.frame(transposed_salmon)

transposed_green <- data.frame(transposed_green)

#Add column "x" that holds numeric values for each library
transposed_red$X <- c(1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
                      6, 6, 6, 6, 7, 7, 7)

transposed_magenta$X <- c(1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
                          6, 6, 6, 6, 7, 7, 7)

transposed_pink$X <- c(1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
                       6, 6, 6, 6, 7, 7, 7)

transposed_salmon$X <- c(1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
                         6, 6, 6, 6, 7, 7, 7)

transposed_green$X <- c(1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
                        6, 6, 6, 6, 7, 7, 7)
#Set "x" as first column
transposed_red <- transposed_red[, c("X", setdiff(names(transposed_red), "X"))]

transposed_magenta <- transposed_magenta[, c("X", setdiff(names(transposed_magenta), "X"))]

transposed_pink <- transposed_pink[, c("X", setdiff(names(transposed_pink), "X"))]

transposed_salmon <- transposed_salmon[, c("X", setdiff(names(transposed_salmon), "X"))]

transposed_green <- transposed_green[, c("X", setdiff(names(transposed_green), "X"))]

#Plot red
melted_red <- melt(transposed_red, id.vars = "X", variable.name = "gene.ID", value.name = "expression" )
head(melted_red)

melted_red$expression <- as.numeric(melted_red$expression)

agg_red <- aggregate(
  x = melted_red[c("expression")],
  by = melted_red[c("gene.ID","X")],
  FUN = mean, na.rm = TRUE)

tiff('red_module_expression.tiff', width = 4.5, height = 1.8, units = 'in', res = 650)

ggplot(data=agg_red, aes(x=jitter(agg_red$X),y=agg_red$expression)) +
  geom_point(size = 0.1, colour="grey", alpha=0.8) +
  geom_path(aes(x=agg_red$X,y=agg_red$expression, group=agg_red$gene.ID), size=0.2, colour="grey", alpha=0.5, linetype="dotted") +
  geom_smooth(level=0.95, colour="red", size=0.5 ,fill="red", alpha=0.5) +
  scale_y_continuous(trans = 'log2', limits= c(2, 16)) +
  scale_x_continuous(breaks = seq(1,7,1)) +
  labs(x = "Developmental Stage", y = "log2 CPM") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "black")) 

dev.off()

#Plot magenta
melted_magenta <- melt(transposed_magenta, id.vars = "X", variable.name = "gene.ID", value.name = "expression" )
head(melted_magenta)

melted_magenta$expression <- as.numeric(melted_magenta$expression)

agg_magenta <- aggregate(
  x = melted_magenta[c("expression")],
  by = melted_magenta[c("gene.ID","X")],
  FUN = mean, na.rm = TRUE)

tiff('Magenta_module_expression.tiff', width = 4.5, height = 1.8, units = 'in', res = 650)

ggplot(data=agg_magenta, aes(x=jitter(agg_magenta$X),y=agg_magenta$expression)) +
  geom_point(size = 0.1, colour="grey", alpha=0.8) +
  geom_path(aes(x=agg_magenta$X,y=agg_magenta$expression, group=agg_magenta$gene.ID), size=0.2, colour="grey", alpha=0.5, linetype="dotted") +
  geom_smooth(level=0.95, colour="magenta", size=0.5 ,fill="magenta", alpha=0.5) +
  scale_y_continuous(trans = 'log2', limits= c(2, 16)) +
  scale_x_continuous(breaks = seq(1,7,1)) +
  labs(x = "Developmental Stage", y = "log2 CPM") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "black")) 

dev.off()

#Plot pink
melted_pink <- melt(transposed_pink, id.vars = "X", variable.name = "gene.ID", value.name = "expression" )
head(melted_pink)

melted_pink$expression <- as.numeric(melted_pink$expression)

agg_pink <- aggregate(
  x = melted_pink[c("expression")],
  by = melted_pink[c("gene.ID","X")],
  FUN = mean, na.rm = TRUE)

tiff('Pink_module_expression.tiff', width = 4.5, height = 1.8, units = 'in', res = 650)

ggplot(data=agg_pink, aes(x=jitter(agg_pink$X),y=agg_pink$expression)) +
  geom_point(size = 0.1, colour="grey", alpha=0.8) +
  geom_path(aes(x=agg_pink$X,y=agg_pink$expression, group=agg_pink$gene.ID), size=0.2, colour="grey", alpha=0.5, linetype="dotted") +
  geom_smooth(level=0.95, colour="pink", size=0.5 ,fill="pink", alpha=0.5) +
  scale_y_continuous(trans = 'log2', limits= c(2, 16)) +
  scale_x_continuous(breaks = seq(1,7,1)) +
  labs(x = "Developmental Stage", y = "log2 CPM") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "black")) 

dev.off()

#Plot salmon
melted_salmon <- melt(transposed_salmon, id.vars = "X", variable.name = "gene.ID", value.name = "expression" )
head(melted_salmon)

melted_salmon$expression <- as.numeric(melted_salmon$expression)

agg_salmon <- aggregate(
  x = melted_salmon[c("expression")],
  by = melted_salmon[c("gene.ID","X")],
  FUN = mean, na.rm = TRUE)

tiff('Salmon_module_expression.tiff', width = 4.5, height = 1.8, units = 'in', res = 650)

ggplot(data=agg_salmon, aes(x=jitter(agg_salmon$X),y=agg_salmon$expression)) +
  geom_point(size = 0.1, colour="grey", alpha=0.8) +
  geom_path(aes(x=agg_salmon$X,y=agg_salmon$expression, group=agg_salmon$gene.ID), size=0.2, colour="grey", alpha=0.5, linetype="dotted") +
  geom_smooth(level=0.95, colour="salmon", size=0.5 ,fill="salmon", alpha=0.5) +
  scale_y_continuous(trans = 'log2', limits= c(2, 16)) +
  scale_x_continuous(breaks = seq(1,7,1)) +
  labs(x = "Developmental Stage", y = "log2 CPM") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "black")) 

dev.off()

#Plot green
melted_green <- melt(transposed_green, id.vars = "X", variable.name = "gene.ID", value.name = "expression" )
head(melted_green)

melted_green$expression <- as.numeric(melted_green$expression)

agg_green <- aggregate(
  x = melted_green[c("expression")],
  by = melted_green[c("gene.ID","X")],
  FUN = mean, na.rm = TRUE)

tiff('green_module_expression.tiff', width = 4.5, height = 1.8, units = 'in', res = 650)

ggplot(data=agg_green, aes(x=jitter(agg_green$X),y=agg_green$expression)) +
  geom_point(size = 0.1, colour="grey", alpha=0.8) +
  geom_path(aes(x=agg_green$X,y=agg_green$expression, group=agg_green$gene.ID), size=0.2, colour="grey", alpha=0.5, linetype="dotted") +
  geom_smooth(level=0.95, colour="green", size=0.5 ,fill="green", alpha=0.5) +
  scale_y_continuous(trans = 'log2', limits= c(2, 16)) +
  scale_x_continuous(breaks = seq(1,7,1)) +
  labs(x = "Developmental Stage", y = "log2 CPM") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "black")) 

dev.off()
#Pulling annotation information using module lists to identify specific genes in each module 

#Read in pairwise annotation file 
evlv_ann <- read.csv("merge_all.csv", stringsAsFactors = FALSE, header = TRUE, sep = ",")

#Read in whole transcriptome annotation files 
human_ann <- read.csv("swissprot_human_whole_trxm.csv", stringsAsFactors = FALSE, header = TRUE, sep = ",")

whole_ann <- read.csv("swissprot_all_whole_trxm.csv", stringsAsFactors = FALSE, header = TRUE, sep = ",")

#Filter annotated gene ids from module list
#red
evlv_ann_red <- filter(evlv_ann, evlv_ann$genes %in% red$genes)

human_red <- filter(human_ann, human_ann$genes %in% red$genes)

all_red <- filter(whole_ann, whole_ann$genes %in% red$genes)

#Magenta
evlv_magenta <- filter(evlv_ann, evlv_ann$genes %in% magenta$genes)

human_magenta <- filter(human_ann, human_ann$genes %in% magenta$genes)

all_magenta <- filter(whole_ann, whole_ann$genes %in% magenta$genes)

#Pink
evlv_pink <- filter(evlv_ann, evlv_ann$genes %in% pink$genes)

human_pink <- filter(human_ann, human_ann$genes %in% pink$genes)

all_pink <- filter(whole_ann, whole_ann$genes %in% pink$genes)

#Salmon
evlv_salmon <- filter(evlv_ann, evlv_ann$genes %in% salmon$genes)

human_salmon <- filter(human_ann, human_ann$genes %in% salmon$genes)

all_salmon <- filter(whole_ann, whole_ann$genes %in% salmon$genes)

#Green 
evlv_green <- filter(evlv_ann, evlv_ann$genes %in% green$genes)

human_green <- filter(human_ann, human_ann$genes %in% green$genes)

all_green <- filter(whole_ann, whole_ann$genes %in% green$genes)

#Write these out as csv 
write.csv(human_red, "human_red.csv")
write.csv(human_magenta, "human_magenta.csv")
write.csv(human_pink, "human_pink.csv")
write.csv(human_salmon, "human_salmon.csv")
write.csv(human_green, "human_green.csv")
write.csv(all_red, "all_red.csv")

write.csv(evlv_ann_red, "evlv_red.csv")
write.csv(evlv_green, "evlv_green.csv")
write.csv(evlv_magenta, "evlv_magenta.csv")
write.csv(evlv_pink, "evlv_pink.csv")

#Read in Camilo's annotations file 
cam_ann <- read.csv("camilo_ann.csv", stringsAsFactors = FALSE, header = TRUE, sep = ",")

# Define a function to rename gene names
rename_genes <- function(df) {
  # Define a regular expression to match the pattern (period and text after it)
  pattern <- "\\..*"
  
  # Loop through each gene name in the "genes" column and rename it
  df$genes <- gsub(pattern, "", df$genes)
  
  return(df)
}

# Rename genes in the dataframe "cam_ann"
cam_ann <- rename_genes(cam_ann)
cam_ann <- cam_ann[,-1]

#Filter for red file since this is the trickiest 
cam_red <- filter(cam_ann, cam_ann$genes %in% red$genes)
write.csv(cam_red, "cam_red.csv")

#Filter for magenta
cam_mag <- filter(cam_ann, cam_ann$genes %in% magenta$genes )
write.csv(cam_mag, "cam_mag.csv")

#Filter for pink
cam_pink <- filter(cam_ann, cam_ann$genes %in% pink$genes )
write.csv(cam_mag, "cam_pink.csv")

#Filter for green
cam_green <- filter(cam_ann, cam_ann$genes %in% green$genes )
write.csv(cam_green, "cam_green.csv")
